name: "CD"

on:
  push: 
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of sonar-analysis
      
      - name: Authenticate to GitHub's docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish the image
        run: |
          docker build . --tag ghcr.io/ardc-ttus/pipeline-tech-talk-with-deno:latest
          docker run ghcr.io/ardc-ttus/pipeline-tech-talk-with-deno:latest
          docker push ghcr.io/ardc-ttus/pipeline-tech-talk-with-deno:latest
        